---
- hosts: localhost
  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap:
        name: [
        ]

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - alacritty
        - discord
        - docker
        - figma
        - firefox 
        - handbrake
        - hiddenbar
        - maccy
        - notion
        - obsidian
        - spotify 
        - reaper
        - rectangle 
        - ticktick 
        - vlc 

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'fish',
          'neovim',
          'node',
          'deno',
          'awscli',
          'terraform',
          'rg',
        ]
        state: present
        update_homebrew: yes

    - name: "Install from Mac app store"
      shell: mas install {{ item }}
      with_items:
        - 497799835 # xcode

    - name: Get the path to fish
      become: false
      local_action: command which fish
      register: fish_path

    - name: "Ensure homebrew fish is in allowed shells"
      lineinfile:
        path: /etc/shells
        line: "{{ fish_path.stdout }}"
      become: true

    - name: Install Starship Prompt
      shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)"

    - name: Set fish as the default shell
      shell: chsh -s $(which fish) {{ lookup('env', 'USER') }}
      become: true

    - name: Install Packer (Neovim)
      shell: git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

    - name: Run Packer (Neovim)
      shell: nvim --headless +PacketSync +qa

    - name: "Set variables"
      set_fact:
        home: "/Users/{{ lookup('env', 'USER') }}/"

    - git:
        repo: https://github.com/thomas-delalande/setup.git
        dest: "{{ home }}/setup"

    - name: Link dotfiles
      shell: ln -s $HOME/setup/.config $HOME/.config && ln -s $HOME/setup/.gitconfig $HOME/.gitconfig && ln -s $HOME/setup/.zshrc $HOME/.tmux.conf && ln -s $HOME/setup/.zshrc $HOME/.tmux.conf

    - name: Create SSH key
      shell: ssh-keygen -t id_rsa -C "80664757+thomas-delalande@users.noreply.github.com"
